In [2]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
np.array(l)

array([1, 2, 3, 4, 5])

In [4]:
np.asarray(l)

array([1, 2, 3, 4, 5])

# np.zeros()

In [5]:
np.zeros(5) #1d array

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros(2,4)

TypeError: Cannot interpret '4' as a data type

In [7]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.zeros((2,3,5)) # 2arrays of size 3x5

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

# np.ones()

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
np.ones((3,2,4)) # 3 arrays of size 2x4

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
5 + np.zeros((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [13]:
a=np.zeros((3,5))

In [14]:
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
a[0]

array([0., 0., 0., 0., 0.])

In [16]:
a[0][0]

0.0

In [17]:
a[:][0]

array([0., 0., 0., 0., 0.])

In [18]:
a[:][0]=5+a[:][0]

In [19]:
a

array([[5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
a[0][:]=1+a[0][:]

In [21]:
a

array([[6., 6., 6., 6., 6.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
a[:][0]

array([6., 6., 6., 6., 6.])

In [23]:
a[0][:]

array([6., 6., 6., 6., 6.])

In [24]:
a[0][1]

6.0

In [25]:
a[:,3]

array([6., 0., 0.])

# IMP

In [26]:
a

array([[6., 6., 6., 6., 6.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
a[:,3]=5+a[:,3] #5 will add to 3rd index column(4th)

In [28]:
a

array([[ 6.,  6.,  6., 11.,  6.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  5.,  0.]])

In [29]:
a[1]# 1st index row

array([0., 0., 0., 5., 0.])

In [30]:
#3rd index column

a[:,3]

array([11.,  5.,  5.])

# np.empty()

In [3]:
np.empty((3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

# np.linspace()

In [5]:
np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [9]:
np.linspace(2,6,12) #12 nos between 2-6

array([2.        , 2.36363636, 2.72727273, 3.09090909, 3.45454545,
       3.81818182, 4.18181818, 4.54545455, 4.90909091, 5.27272727,
       5.63636364, 6.        ])

In [ ]:
#endpoint=False means end value will not included

In [12]:
np.linspace(2,5,10,endpoint=False)

array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7])

In [13]:
#retstep

In [14]:
np.linspace(2,5,10,endpoint=False,retstep=True)

(array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7]), 0.3)

In [17]:
np.linspace(2,5,50,endpoint=False,retstep=True)

(array([2.  , 2.06, 2.12, 2.18, 2.24, 2.3 , 2.36, 2.42, 2.48, 2.54, 2.6 ,
        2.66, 2.72, 2.78, 2.84, 2.9 , 2.96, 3.02, 3.08, 3.14, 3.2 , 3.26,
        3.32, 3.38, 3.44, 3.5 , 3.56, 3.62, 3.68, 3.74, 3.8 , 3.86, 3.92,
        3.98, 4.04, 4.1 , 4.16, 4.22, 4.28, 4.34, 4.4 , 4.46, 4.52, 4.58,
        4.64, 4.7 , 4.76, 4.82, 4.88, 4.94]),
 0.06)

# reshape

In [11]:
#make the above 3x4

np.linspace(2,6,12).reshape(3,4)

array([[2.        , 2.36363636, 2.72727273, 3.09090909],
       [3.45454545, 3.81818182, 4.18181818, 4.54545455],
       [4.90909091, 5.27272727, 5.63636364, 6.        ]])

# logspace()

In [20]:
#same as linspace but gives log of the value

In [23]:
np.logspace

<function numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)>

In [18]:
np.logspace(2,6)

array([1.00000000e+02, 1.20679264e+02, 1.45634848e+02, 1.75751062e+02,
       2.12095089e+02, 2.55954792e+02, 3.08884360e+02, 3.72759372e+02,
       4.49843267e+02, 5.42867544e+02, 6.55128557e+02, 7.90604321e+02,
       9.54095476e+02, 1.15139540e+03, 1.38949549e+03, 1.67683294e+03,
       2.02358965e+03, 2.44205309e+03, 2.94705170e+03, 3.55648031e+03,
       4.29193426e+03, 5.17947468e+03, 6.25055193e+03, 7.54312006e+03,
       9.10298178e+03, 1.09854114e+04, 1.32571137e+04, 1.59985872e+04,
       1.93069773e+04, 2.32995181e+04, 2.81176870e+04, 3.39322177e+04,
       4.09491506e+04, 4.94171336e+04, 5.96362332e+04, 7.19685673e+04,
       8.68511374e+04, 1.04811313e+05, 1.26485522e+05, 1.52641797e+05,
       1.84206997e+05, 2.22299648e+05, 2.68269580e+05, 3.23745754e+05,
       3.90693994e+05, 4.71486636e+05, 5.68986603e+05, 6.86648845e+05,
       8.28642773e+05, 1.00000000e+06])

In [19]:
np.logspace(2,6,10)

array([1.00000000e+02, 2.78255940e+02, 7.74263683e+02, 2.15443469e+03,
       5.99484250e+03, 1.66810054e+04, 4.64158883e+04, 1.29154967e+05,
       3.59381366e+05, 1.00000000e+06])

In [22]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [24]:
a=np.arange(16)

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
a=a.reshape(4,4)

In [29]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
a.max()

15

In [31]:
a.min()

0

In [32]:
a=np.arange(4,20).reshape(4,4)

a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
a.max()

19

# IMP

In [34]:
a=np.arange(4,40).reshape(3,6,2)

In [35]:
a

array([[[ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [36]:
a.max()

39

In [37]:
a.max(axis=1) #column wise max

array([[14, 15],
       [26, 27],
       [38, 39]])

In [38]:
a.max(axis=0)

array([[28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [39]:
b=np.arange(4,40).reshape(6,6)

b

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [42]:
b.max(axis=1)#column wise comparison(4-5-6-7-8-9)--9,comparing vertically

array([ 9, 15, 21, 27, 33, 39])

In [41]:
b.max(axis=0)#comparing horizontally(4-10-16-22-28-34)--34

array([34, 35, 36, 37, 38, 39])

In [43]:
b[0,3]

7